### ISSUE TITLE
SEO - canonical

### ISSUE THREAD

**Issue by ThanhNguyenDo** [s-cart/s-cart#100]
"link rel="canonical" href="{{$canonical}}"

cần thêm thuộc tính "canonical" trong description để SEO cho trường hợp muốn trỏ về 1 page chính
cần tự động xử lý "canonical" cho trường hợp thêm parameter trên query, ví dụ: product/may-tinh-ban?color=red&price=1 nên trỏ về trang chính là product/may-tinh-ban thôi

**Comment by lanhktc** [comment]
Cảm ơn bạn.
Chỉnh sửa sẽ được cập nhật trong phát hành tiếp theo.

**Comment by ThanhNguyenDo** [comment]
chỉ là ý tưởng, đang nghĩ lại là viết plugin, có thể là  làm cách ở trên, nhưng h nghĩ lại chắc viết plugin có thêm 1 plugin để config riêng cho cái canonical, mỗi controller sẽ check nếu enable plugin này sẽ add page id, page type vào table này để lấy canonical , khi create/delete page sẽ add/remove thông tin page đó vào table mới của plugin này 
Trường hợp k có canonical, nhưng có query param sẽ tự tính để trỏ về page chính k có query param, có thể có config enable cho chỗ này, 1 config cho SEO. 

có thể sẽ làm tương tự cho các meta data khác, nhưng h sẽ vẫn giữ flow cũ, lưu lại bảng mới để analysis chứ k có tác dụng trên page.
