### ISSUE TITLE
google-site-verification meta  tag

### ISSUE THREAD

**Issue by ThanhNguyenDo** [s-cart/s-cart#103]
**Is your feature request related to a problem? Please describe.**
Tích  hợp google search console để quản lý việc SEO

**Describe the solution you'd like**
Add the meta html to head tag
Có  chỗ cấu hình để điền vào  key content ở SEO trên trang admin và  thêm  
<meta name="google-site-verification" content="..."/> vào  trang  front

**Comment by lanhktc** [comment]
Chúc năng này chúng ta có thể sử dụng các block content
![image](https://user-images.githubusercontent.com/13057715/142767244-c531f782-8a38-4fcd-b1f1-64ee62daee1e.png)
