### ISSUE TITLE
Trang tra cứu nhanh các class và function

### ISSUE THREAD

**Issue by hoangnamitc** [s-cart/s-cart#109]
Xin chào,

Hiện tại trong source có rất nhiều function và method và class được viết mới "sc_xxx()"
Nhưng thay vì đọc nội dung từng hàm, thậm chí đọc xong vẫn mơ hồ thì mong rằng sẽ có trang tra cứu tên hàm và chức năng tương tự như trang sau của Laravel thì tuyệt vời ạ!

Trang mẫu: https://laravel.com/api/8.x/

**Comment by s-cart** [comment]
@hoangnamitc Tài liệu sẽ sớm hoàn thiện trong thời gian tới :)
