### ISSUE TITLE
Use of undefined constant SC_PRODUCT_NEW

### ISSUE THREAD

**Issue by nguyendachuy** [s-cart/s-cart#11]
I get an error after I create a new template and run it

Message: Facade\Ignition\Exceptions\ViewException
Use of undefined constant **SC_PRODUCT_NEW** - assumed 'SC_PRODUCT_NEW' (this will throw an Error in a future version of PHP) (View: ********\resources\views\templates\newtemplate\screen\shop_home.blade.php) 

Where are these Global Variables set, I cannot find it in source code?

**PHP version: 7.2.31**

**Comment by lanhktc** [comment]
Fixed in release 2.1.5 :)
