### ISSUE TITLE
method setMoreWhere use with is null

### ISSUE THREAD

**Issue by hoangnamitc** [s-cart/s-cart#110]
Xin chao`,

Tôi đọc tài liệu thấy có phương thức setMoreWhere() dùng để thêm điều kiện tùy chọn cho câu truy vấn,
tuy nhiên nếu ko dùng =|like mà muốn sử dụng với `IS NULL` hoặc` IS NOT NULL` thì sử dụng như thế nào ạ?

Cảm ơn !

**Comment by hoangnamitc** [comment]
Thiết nghĩ nên cho tham số truyền vào có thể là array hoặc string để truyền luôn rawQuery

vd:  setMoreWhere('column IS NULL')

**Comment by hoangnamitc** [comment]
<img width="1075" alt="image" src="https://user-images.githubusercontent.com/7042462/161410195-0168be12-0597-4d8c-92b6-fc06ae34b90b.png">

**Comment by s-cart** [comment]
@hoangnamitc Thử cập nhật core và sử dụng `setMoreQuery`
->setMoreQuery(
[
 'keyIsOperationOfLaravel' => array()
]
)

Ví dụ:
->setMoreQuery(
[
 'where' => ['name','like','%abc']
]
)
->setMoreQuery(
[
 'whereNull' => ['name']
]
)
->setMoreQuery(
[
 'whereIn' => ['name', ['thanks','for','all']]
]
)
->setMoreQuery(
[
 'whereColumn' => ['name', 'title']
]
)
....
Chi tiết:
https://github.com/s-cart/core/commit/f07fa8aa185f2ff379b263ab640663953ecad996
