### ISSUE TITLE
s-cart-2022-03-08.sql corrupted or encrypted

### ISSUE THREAD

**Issue by mastudillot** [s-cart/s-cart#111]
**Describe the bug**
This file s-cart-2022-03-08.sql is corrupted.

**To Reproduce**
1. composer install
2. Go to /vendor/s-cart/core/src/DB
3. Check the file s-cart-2022-03-08.sql

**Expected behavior**
The file without being encrypted or corrupted

**Screenshots**
![image](https://user-images.githubusercontent.com/36648048/164942695-e9e074d3-9bd9-4b5f-beb6-7c16f6cf3995.png)

**Comment by s-cart** [comment]
@mastudillot Thanks for report. Fixed sample data 
https://github.com/s-cart/core/tree/master/src/DB
