### ISSUE TITLE
Sub-Categories issue !!

### ISSUE THREAD

**Issue by amir-s86** [s-cart/s-cart#115]
1 - After creating subcategories I can't view or even access it from the front-end .
Even when I add contents to it is not possible to display the contents from the front-end (No items found) .
2 - the url  : http://site/sc_admin/store_modify_layout  
shows (404 NOT FOUND) .

could you please provide a fix 

many thanks in advance ..

**Comment by s-cart** [comment]
@amir-s86 
>Even when I add contents to it is not possible to display the contents from the front-end (No items found) .
S-cart version? Give me screenshots or step-by-step

**Comment by amir-s86** [comment]
![1](https://user-images.githubusercontent.com/44472553/169284267-bf909627-c6c7-4cfc-ae66-94b8076d9be2.jpg)
![2](https://user-images.githubusercontent.com/44472553/169284273-bcd8715f-96aa-4404-ae4e-5efbdc7ece2b.jpg)

**Comment by s-cart** [comment]
@amir-s86 
Because you don't have any posts (item) in that category

**Comment by amir-s86** [comment]
I want to make sub categories under this category and add the items to the Sub-categories  but the Sub-categories didn't shows in the parent category
