### ISSUE TITLE
Amazon SES Email is not working

### ISSUE THREAD

**Issue by arungowda325** [s-cart/s-cart#127]
Added a Amazon SES Email SMTP settings in admin -> System config . But jobs are not inserting

**Comment by arungowda325** [comment]
Succees and failure jobs are not inserted to table jobs.

**Comment by s-cart** [comment]
By default, sending mail does not go through job

**Comment by arungowda325** [comment]
Then how to enable automated emails for the below events?

ON/OFF send mail |  
Use send mail queue (*) |  
Send order success to admin |  
Send order success to customer |  
Send order success to customer with pdf invoice |  
Customer verification |  
Send email welcome |  
Send email contact to admin |  
Send email forgot |  
Use SMTP config |

**Comment by s-cart** [comment]
Yuo need enable "ON/OFF send mail" and "Use send mail queue"
![image](https://github.com/s-cart/s-cart/assets/63009096/2ef7120d-91d8-4507-8488-6f81b8eb094f)

**Comment by arungowda325** [comment]
Already enabled. But jobs are not inserted into the table. Please let me know how to debug this.
<img width="1015" alt="image" src="https://github.com/s-cart/s-cart/assets/38986419/841d9399-409b-40b3-96e4-6f0f62e133fa">

**Comment by s-cart** [comment]
Try check log error in s-cart-folder\storage\logs

**Comment by arungowda325** [comment]
I have disabled Send Mail Queue (*), and now emails are working fine. Thanks for the support.

<img width="469" alt="image" src="https://github.com/s-cart/s-cart/assets/38986419/a74d24e5-b5c6-4ed0-936f-3a0e09eb4c58">
