### ISSUE TITLE
blug

### ISSUE THREAD

**Issue by namdaik** [s-cart/s-cart#13]
![image](https://user-images.githubusercontent.com/19622562/84994705-4aa77580-b175-11ea-9ec6-8ed7355b4ffb.png)
![image](https://user-images.githubusercontent.com/19622562/84994737-55faa100-b175-11ea-9833-bd07423caa64.png)

**Comment by namdaik** [comment]
![image](https://user-images.githubusercontent.com/19622562/84995244-f781f280-b175-11ea-99f7-8a1b12048313.png)
các hàm filemtime  cần thêm public_path

**Comment by lanhktc** [comment]
Thanks. Fixed in release v2.1.9 :)
