### ISSUE TITLE
Product variant's logic 

### ISSUE THREAD

**Issue by rsmmukesh** [s-cart/s-cart#19]
Product variant's logic 

From the below image we have variants RED,GREEN,100g, 200g. Then we can buy RED -100g , RED - 200 g , GREEN-100g , GREEN - 200g .

1. But there is a situation i dont have product RED - 200g but i have GREEN - 200 g . then how i can remove it from page ?
2. There is no option to set stock to each variant.
3. I dont see option to show price including tax in product page.

Application is super and thanks a lot.

![prod](https://user-images.githubusercontent.com/11568085/91630945-6049de80-e9f3-11ea-8081-3ce173ede01f.PNG)

**Comment by rsmmukesh** [comment]
@lanhktc ... are you working on the above problem I mentioned? Or it take time?

**Comment by lanhktc** [comment]
> @lanhktc ... are you working on the above problem I mentioned? Or it take time?

Unfortunately, SC does not yet support quantities for each attribute. Instead, you can separate your attributes into individual products.

**Comment by emaalouf** [comment]
Is it possible to add quantities of a product without attributes and display them on the frontend? If yes, how?
