### ISSUE TITLE
500 internal server error

### ISSUE THREAD

**Issue by thinklifepot** [s-cart/s-cart#21]
**Describe the bug**
After i have installed the s-cart using the install.php, i can't login to the admin, it shows 500 error

**To Reproduce**
1. download s-cart
2. install it through the install.php
3. go to /admin

**Screenshots**
![Screenshot from 2020-09-01 12-43-23](https://user-images.githubusercontent.com/67321152/91845335-dc8d2d80-ec50-11ea-8b0c-c5f0ea9e58b8.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - Browser: chrome
 - Version: Version 84.0.4147.105 (Official Build) (64-bit)

**Comment by lanhktc** [comment]
Send me the log file, or turn on the debug function to display the error screen

**Comment by thinklifepot** [comment]
here is the log file 

`Mon Aug 31 13:39:03.272105 2020] [autoindex:error] [pid 14914] [client 127.0.0.1:35036] AH01276: Cannot serve directory /home/ozioma/web/amaahia/public/admin/: No matching DirectoryIndex (index.html,index.cgi,index.pl,index.php,index.xhtml,index.htm) found, and server-generated directory index forbidden by Options directive
[Mon Aug 31 13:47:29.032015 2020] [autoindex:error] [pid 15220] [client 127.0.0.1:36492] AH01276: Cannot serve directory /home/ozioma/web/amaahia/public/admin/: No matching DirectoryIndex (index.html,index.cgi,index.pl,index.php,index.xhtml,index.htm) found, and server-generated directory index forbidden by Options directive
[Mon Aug 31 13:47:33.571939 2020] [autoindex:error] [pid 15220] [client 127.0.0.1:36492] AH01276: Cannot serve directory /home/ozioma/web/amaahia/public/admin/: No matching DirectoryIndex (index.html,index.cgi,index.pl,index.php,index.xhtml,index.htm) found, and server-generated directory index forbidden by Options directive
[Mon Aug 31 13:47:34.482655 2020] [autoindex:error] [pid 15220] [client 127.0.0.1:36492] AH01276: Cannot serve directory /home/ozioma/web/amaahia/public/admin/: No matching DirectoryIndex (index.html,index.cgi,index.pl,index.php,index.xhtml,index.htm) found, and server-generated directory index forbidden by Options directive
[Mon Aug 31 13:47:34.917165 2020] [autoindex:error] [pid 15220] [client 127.0.0.1:36492] AH01276: Cannot serve directory /home/ozioma/web/amaahia/public/admin/: No matching DirectoryIndex (index.html,index.cgi,index.pl,index.php,index.xhtml,index.htm) found, and server-generated directory index forbidden by Options directive
[Mon Aug 31 13:47:35.134235 2020] [autoindex:error] [pid 15220] [client 127.0.0.1:36492] AH01276: Cannot serve directory /home/ozioma/web/amaahia/public/admin/: No matching DirectoryIndex (index.html,index.cgi,index.pl,index.php,index.xhtml,index.htm) found, and server-generated directory index forbidden by Options directive
[Mon Aug 31 13:47:35.330865 2020] [autoindex:error] [pid 15220] [client 127.0.0.1:36492] AH01276: Cannot serve directory /home/ozioma/web/amaahia/public/admin/: No matching DirectoryIndex (index.html,index.cgi,index.pl,index.php,index.xhtml,index.htm) found, and server-generated directory index forbidden by Options directive
[Mon Aug 31 13:47:35.539347 2020] [autoindex:error] [pid 15220] [client 127.0.0.1:36492] AH01276: Cannot serve directory /home/ozioma/web/amaahia/public/admin/: No matching DirectoryIndex (index.html,index.cgi,index.pl,index.php,index.xhtml,index.htm) found, and server-generated directory index forbidden by Options directive
[Mon Aug 31 13:47:35.765611 2020] [autoindex:error] [pid 15220] [client 127.0.0.1:36492] AH01276: Cannot serve directory /home/ozioma/web/amaahia/public/admin/: No matching DirectoryIndex (index.html,index.cgi,index.pl,index.php,index.xhtml,index.htm) found, and server-generated directory index forbidden by Options directive
[Mon Aug 31 14:11:26.399704 2020] [autoindex:error] [pid 14914] [client 127.0.0.1:37446] AH01276: Cannot serve directory /home/ozioma/web/amaahia/public/admin/: No matching DirectoryIndex (index.html,index.cgi,index.pl,index.php,index.xhtml,index.htm) found, and server-generated directory index forbidden by Options directive
[Tue Sep 01 12:39:56.680407 2020] [autoindex:error] [pid 1420] [client 127.0.0.1:38574] AH01276: Cannot serve directory /home/ozioma/web/amaahia/public/admin/: No matching DirectoryIndex (index.html,index.cgi,index.pl,index.php,index.xhtml,index.htm) found, and server-generated directory index forbidden by Options directive`

**Comment by lanhktc** [comment]
The log file shows the access to your public/admin directory. Something seems wrong here:
1. In the .env file, set APP_DEBUG = true
2. Then, give me screen of the website's error page.
