### ISSUE TITLE
error after install paypal plugin

### ISSUE THREAD

**Issue by razvanrun** [s-cart/s-cart#22]
After I install the paypal plugin, suddenly, I get an "error 500" when I try to 
access sc_admin/plugin/payment, and when I try to complete the order. 

Call to undefined method App\Models\ShopOrderStatus::mapValue() (View: /home/razvanrun/Documents/web/s-cart/resources/views/admin/screen/plugin.blade.php)

**Comment by lanhktc** [comment]
What SC version do you install?
It should be noted that, plugin must be installed for specified SC versions. Currently SC3x does not support paypal plugin

**Comment by razvanrun** [comment]
> What SC version do you install?
> It should be noted that, plugin must be installed for specified SC versions. Currently SC3x does not support paypal plugin

Yes, you're right. Thank you for your answear.

**Comment by lanhktc** [comment]
@razvanrun New Paypal for SCart 3.x. Pls read guid.
https://s-cart.org/plugin/paypal-express-for-s-cart_15990885835f5027c75f89d.html
