### ISSUE TITLE
Manual Installation error on localhost

### ISSUE THREAD

**Issue by ozilion** [s-cart/s-cart#23]
Hi, 

I saw your product in one of facebook laravel group and decided to try it. I am trying to install it on our Wiindows server 2012 server doing manual installation but getting error at generating app_key step as below:

`PS W:\scart> php artisan key:generate

   Illuminate\Database\QueryException

  SQLSTATE[HY000] [1045] Access denied for user 'scart'@'localhost' (using password: YES) (SQL: select `value`, `key` from `sc_admin_config` where `store_id` is null)

  at W:\scart\vendor\laravel\framework\src\Illuminate\Database\Connection.php:671
    667|         // If an exception occurs when attempting to run a query, we'll format the error
    668|         // message to include the bindings with SQL, which will make this exception a
    669|         // lot more helpful to the developer instead of just the database's errors.
    670|         catch (Exception $e) {
  > 671|             throw new QueryException(
    672|                 $query, $this->prepareBindings($bindings), $e
    673|             );
    674|         }
    675|

  1   [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}(Object(App\Providers\RouteServiceProvider))

  2   W:\scart\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php:70
      PDOException::("SQLSTATE[HY000] [1045] Access denied for user 'scart'@'localhost' (using password: YES)")`

I created database, imported .sql file in database folder and set all database connetion info in .env file but still getting that error.

How can i solve this please?

**Comment by lanhktc** [comment]
You need to check that the data information in the .env file is correct
