### ISSUE TITLE
ErrorException get_cfg_var() has been disabled for security reasons

### ISSUE THREAD

**Issue by Shayboniyshoh** [s-cart/s-cart#26]
Hi Sir,

Thanks for this an amazing job you have done!
 I have an issue when adding a new product in the admin panel saying that supplier id must be a number. and I turned on debugging and it showed me the following error:

ErrorException
get_cfg_var() has been disabled for security reasons.
![Screenshot (44)](https://user-images.githubusercontent.com/47345004/92272145-73ccdc00-ef02-11ea-8d23-8d77089db3f8.png)

vendor/symfony/var-dumper/Dumper/CliDumper.php:86

**Comment by lanhktc** [comment]
@Shayboniyshoh  Thanks report.
Fixed https://github.com/s-cart/s-cart/commit/c3446c8a6feb06ab8721fd63c6d82f59f8939eee
