### ISSUE TITLE
During Install.php i found DB error 

### ISSUE THREAD

**Issue by roconmachine** [s-cart/s-cart#27]
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (SQL: alter table `jobs` add index `jobs_queue_index`(`queue`))

**Comment by lanhktc** [comment]
@roconmachine  try it https://github.com/s-cart/s-cart/commit/d22bf158f206a4802cce349cca768d263fb42b41
