### ISSUE TITLE
http://fm.smartgrad.co.uk/  Server Error || 500 

### ISSUE THREAD

**Issue by roconmachine** [s-cart/s-cart#28]
I follow all the instructions from here https://s-cart.org/docs/3.0/installation.html but I found the end of the installation is server error | 500 .

how to resolve it ?

i get error 

ErrorException
Trying to get property 'code' of non-object 
 
when I set debug true in inv file.

**Comment by lanhktc** [comment]
Error not reading template folder. How to install automatically or manually?

**Comment by roconmachine** [comment]
composer. i got the error and fix it.
