### ISSUE TITLE
Phone format is invalid

### ISSUE THREAD

**Issue by Shayboniyshoh** [s-cart/s-cart#29]
Hello!

Having trouble when click to CHECKOUT button on a view cart page. phone format is invalid. I have tried all types of format, but could not solve it.

![Screenshot (50)](https://user-images.githubusercontent.com/47345004/92387707-7e1fed80-f12f-11ea-9d52-fd10e8378892.png)

**Comment by lanhktc** [comment]
Format phone numbers starting with 0

**Comment by Shayboniyshoh** [comment]
not all countries phone format starts with 0. how can I change it?

**Comment by lanhktc** [comment]
Change it:  app/Http/Controllers/Auth/AuthTrait.php, line 74-76.
required|regex:/^0[^0][0-9\-]{7,13}$ -> required|regex:/[0-9\-]{7,13}$
