### ISSUE TITLE
TIMESTAMP error

### ISSUE THREAD

**Issue by dhonxean** [s-cart/s-cart#31]
Having this error. How can I solve this? 

Illuminate\Database\QueryException
SQLSTATE[HY000]: General error: 1525 Incorrect TIMESTAMP value: '2019-09' (SQL: select DATE_FORMAT(created_at, "%Y-%m") AS ym, SUM(total/exchange_rate) AS total_amount from `sc_shop_order` where created_at >= DATE_FORMAT(DATE_SUB(CURRENT_DATE(), INTERVAL 12 MONTH), "%Y-%m") group by `ym`)

![image](https://user-images.githubusercontent.com/31211845/92678591-f289a500-f358-11ea-8045-af338bec84fa.png)

**Comment by lanhktc** [comment]
> Having this error. How can I solve this?
> 
> Illuminate\Database\QueryException
> SQLSTATE[HY000]: General error: 1525 Incorrect TIMESTAMP value: '2019-09' (SQL: select DATE_FORMAT(created_at, "%Y-%m") AS ym, SUM(total/exchange_rate) AS total_amount from `sc_shop_order` where created_at >= DATE_FORMAT(DATE_SUB(CURRENT_DATE(), INTERVAL 12 MONTH), "%Y-%m") group by `ym`)
> 
> ![image](https://user-images.githubusercontent.com/31211845/92678591-f289a500-f358-11ea-8045-af338bec84fa.png)

pls download last version

**Comment by dhonxean** [comment]
I've already downloaded the last version but still giving this problem. 
![image](https://user-images.githubusercontent.com/31211845/92774016-a9286c80-f3cf-11ea-863b-f013f5309eb1.png)

**Comment by dhonxean** [comment]
Fixed it by adding -%d in ShopOrder.php

**Comment by lanhktc** [comment]
@dhonxean https://github.com/s-cart/s-cart/commit/21665ed4563e4c17b1dbc1813fbc1cb49d03e81b
