### ISSUE TITLE
Any documentation on Plugin manager?

### ISSUE THREAD

**Issue by Nejcc** [s-cart/s-cart#34]
Do you have any specifics documentation on plugin manager like using as separate package that can be applied to laravel  and update via composer ? Mapping (Controllers, Models, Middlewares, Jobs, Migrations, Views, etc... ) ? 

Kind Thank you

**Comment by lanhktc** [comment]
@Nejcc https://s-cart.org/docs/3.0/how-to-install-module-extension.html
