### ISSUE TITLE
Config customer is not working while change any filed value and required

### ISSUE THREAD

**Issue by roconmachine** [s-cart/s-cart#40]
**Describe the bug**
Config customer is not working while change any filed value and required

**To Reproduce**
1. Go to sc_admin/customer_config
2. Click on any of the field value and required
3. check-in the web that no change happened

**Comment by lanhktc** [comment]
Your version? 
Can you give screenshot?

**Comment by roconmachine** [comment]
i fix it by removing the conflicted config of a different stores.

**Comment by roconmachine** [comment]
I am suffering from this issue. I am trying to fix others and most of them
are fixed.

but I find no plugin that can integrate stripe.

thanks
