### ISSUE TITLE
can't change nor see orders in other language

### ISSUE THREAD

**Issue by Shayboniyshoh** [s-cart/s-cart#41]
hi, I am having an issue with changing orders from admin dashboard or can't see them in other language that I have added. In the lang folder, I copy and paster english version and changed it to other language. I have translated all to that language. Everything working fine except that I can't see nor change orders from dashboard. and having "500 error". 

![Screenshot (71)](https://user-images.githubusercontent.com/47345004/93378233-969daf80-f875-11ea-9c5a-cb080d81a7ab.png)
![Screenshot (72)](https://user-images.githubusercontent.com/47345004/93378239-98677300-f875-11ea-9771-1fe439555ae7.png)

**Comment by lanhktc** [comment]
@Shayboniyshoh your error log ?

**Comment by Shayboniyshoh** [comment]
> @Shayboniyshoh your error log ?

in the language other than Default English and Tai lang, When I click to any order from the notification list on the first picture above, I am having 500 Server Error as below picture.

![Screenshot (75)](https://user-images.githubusercontent.com/47345004/93706515-6b021a00-fb40-11ea-8d2b-639f7d1a6d79.png)

**Comment by arteshuk** [comment]
Hi!
ErrorException
Trying to access array offset on value of type null
\app\Models\ShopProduct.php:252
foreach ($products as $key => $product) {
        $arrProduct[$product->id] = $product->getFull()['name'] . ' (' . $product->sku . ')'; // here 252 line
}
