### ISSUE TITLE
Single Store Multi-Vendor

### ISSUE THREAD

**Issue by illuminate3** [s-cart/s-cart#42]
Hi, I see that you can do multi-store with separate database. Are you planning to do 1 store multi-vendor?
If not, what should I change to do this? (not code but idea on how to)

**Comment by lanhktc** [comment]
> Hi, I see that you can do multi-store with separate database. Are you planning to do 1 store multi-vendor?
> If not, what should I change to do this? (not code but idea on how to)

Yes, we are collaborating with developers to build a professional multi-store module

**Comment by illuminate3** [comment]
Awesome!

I hate to ask but do you have a release date?

**Comment by lanhktc** [comment]
> Awesome!
> 
> I hate to ask but do you have a release date?

We expect to have a good signal towards the end of September

**Comment by SakuraCart** [comment]
Things are looking good!

Is multi-vendor single store a plugin? I couldn't find the setting.

**Comment by lanhktc** [comment]
It will be a plugin and is in the final stages of development

**Comment by rakib6120** [comment]
how long it take?
