### ISSUE TITLE
Plugin System

### ISSUE THREAD

**Issue by illuminate3** [s-cart/s-cart#43]
Thank you for a wonderful e-commerce system.

I was wondering, is the plugin API just a call to your main store and it grabs a list to install?
Are you going to put the on GitHub too?

I do have a problem with installing plugins and themes through the API system on my local machine. When I get a chance, I will see what I can debug.

**Comment by lanhktc** [comment]
S-Cart is aimed at general users, can install plugins with just a click. Therefore, plugins and templates will be supported through the library API.

**Comment by illuminate3** [comment]
I understand.

How did you setup the server side to accept the API calls?
