### ISSUE TITLE
How to change required field to not required

### ISSUE THREAD

**Issue by Shayboniyshoh** [s-cart/s-cart#44]
Hello!!!

When I try to add a new product, I don't wanna add Price Promotion. But I can't add any product without Price Promotion beacuse of Required input. How Can I change the input from required to not required!?

**Comment by lanhktc** [comment]
@Shayboniyshoh  Try it https://github.com/s-cart/s-cart/commit/c3446c8a6feb06ab8721fd63c6d82f59f8939eee#diff-ab8a937b369777105e684c244c4fab9fR865
