### ISSUE TITLE
Upgrade system / Docs

### ISSUE THREAD

**Issue by quangbahoa** [s-cart/s-cart#45]
Hello,

May I know how to upgrade to latest version? Im try via `composer update` but not work.

Thanks

**Comment by s-cart** [comment]
> Hello,
> 
> May I know how to upgrade to latest version? Im try via `composer update` but not work.
> 
> Thanks

Unfortunately, at the moment we do not support upgrading S-Cart via the command line. We hope the functionality will be available in the near future.
