### ISSUE TITLE
can't add title, keyword, and description

### ISSUE THREAD

**Issue by Shayboniyshoh** [s-cart/s-cart#46]
Hello, thank you very much for such an amazing job!!!

I have four languages overall. I have added two more languages. but I can't add title, keyword, and description for other languages from the admin panel as in the screenshot below:

![Screenshot (106)](https://user-images.githubusercontent.com/47345004/95232573-23f17580-081e-11eb-9a45-a65471a92e7e.png)

could you please help with that? How can I add them?

**Comment by lanhktc** [comment]
For new language, https://github.com/s-cart/s-cart/commit/0ec61f6b37a722d588f1357030e1a00bc991c3b0
