### ISSUE TITLE
Suddenly Unable to Login to admin account anymore

### ISSUE THREAD

**Issue by nearbyseller** [s-cart/s-cart#49]
I've been using the cart for a while now and everything is working just fine... Suddenly, i'm unable to login, I don't know the cause of this problem and hope i get a solution.

**Comment by lanhktc** [comment]
> I've been using the cart for a while now and everything is working just fine... Suddenly, i'm unable to login, I don't know the cause of this problem and hope i get a solution.

Log error or screenshort?
