### ISSUE TITLE
Production Server Problems

### ISSUE THREAD

**Issue by fkurtulus** [s-cart/s-cart#5]
Hello sir, 
We develop a project using s-cart, in the localhost system runs normally. But in the production server, it does not work well, such as when click switch language, it refreshes the page but not change language but when I click a link inside the page, new page displays, and change language. The same thing in add to cart button too, it says product added but in cart no any product, refresh page product display in the cart,

Weird thing is that, when a user add a product in his cart, another user can see their product in his cart. 

I guess it's about caching or session problem but could not find the solution.

**Comment by lanhktc** [comment]
I am trying to find out what your problem is.  Our demo is still working well.  Any additional information to find the cause is welcome.

**Comment by fkurtulus** [comment]
You can see below link what i told you, if you try to add a product to cart, you will see what I told,
http://hitame.com.tr/public/product/pelesenk.html

**Comment by fkurtulus** [comment]
OR change language or currency you will see,

**Comment by fkurtulus** [comment]
When you click add to cart, it adds but display in cart takes time, really weird. In local server it is runnig normal.

**Comment by lanhktc** [comment]
I agree with you that you are having trouble processing session on your website.
But it seems to be a delay when retrieving the latest session value to use. Sometimes it returns the latest value immediately.
But that is not enough for us to find the exact cause of the problem.

**Comment by fkurtulus** [comment]
I can share what you want with you. Really weird because ther run in local server,

**Comment by fkurtulus** [comment]
I thing problem is a limit of file session, but could not find the solution.

**Comment by fkurtulus** [comment]
I changed the server, working normal now,
