### ISSUE TITLE
Cant Create new Currency

### ISSUE THREAD

**Issue by lentinifernandes** [s-cart/s-cart#50]
**Describe the bug**

**To Reproduce**
1. Go to 'Localisation'
2. Click on 'Currency'
3. Click on 'Add new Currency'
4. See error - It will redirect you to the same place

**Expected behavior**
Expected to open the page to register a new currency

**Desktop (please complete the following information):**
 - Browser Chrome
 - Version 86.0.4240.193

**Comment by lanhktc** [comment]
Yes, it is a bug.
Fixed: https://github.com/s-cart/core/commit/057a8abca17ad93d698b21dd47382faf28dbe0f3
For S-Cart from 4.3, you can fix error via command line "php composer.phar update s-cart/core"
thanks report.
