### ISSUE TITLE
add product repeater issue

### ISSUE THREAD

**Issue by WaelMz** [s-cart/s-cart#53]
**Describe the bug**
repeaters ( Select products in group,Select products build ) return HTML as string instead of rendered HTML , i try to browse the demo store and repeaters working without any issues 

**To Reproduce**
1. Go to 'add product'
2. Select 'build or group'
3. Scroll down to 'repeaters [ Select products in group,Select products build ]'
4. Click add

**Expected behavior**
expected to show rendered HTML

**Screenshots** 
![image](https://user-images.githubusercontent.com/33140498/103357140-1d8c3600-4abb-11eb-817f-f9e32c0f0686.png)
![image](https://user-images.githubusercontent.com/33140498/103357180-3694e700-4abb-11eb-9ba0-e26c551aa4e2.png)

**Desktop (please complete the following information):**
 - Browser [Firefox]

**Additional context**
any idea what's the problem

**Comment by lanhktc** [comment]
Fixed in release 4.5.1 https://github.com/s-cart/s-cart/releases/tag/v4.5
You can use "composer update s-cart/core" to fix.
