### ISSUE TITLE
banner_image view ( hardcoded ) title and description

### ISSUE THREAD

**Issue by WaelMz** [s-cart/s-cart#54]
banner_image view must show database records ( hard coded founded )

view path : resources\views\templates\s-cart-light\block\banner_image.blade.php

![image](https://user-images.githubusercontent.com/33140498/103389061-50631800-4b15-11eb-97e4-d996cb25722b.png)

**Comment by lanhktc** [comment]
This problem will fix in next release

**Comment by lanhktc** [comment]
Fixed S-Cart 5.0!
