### ISSUE TITLE
phone number validation is not working for a global usage

### ISSUE THREAD

**Issue by humble92** [s-cart/s-cart#56]
The cart is designed for global usage, but phone validation is not for that purpose.

The validation requres the string starts with 0, but some other countries it is not required, 
e.g. in Candada, it can begin 604, 778, and so on.

Therefore, it should be modified for global usage.
Thanks for your effort.

**Comment by lanhktc** [comment]
You can manually change the phone number condition (phone_required) in the config / validation.php configuration file.
Use "php artisan sc: customsize admin" to bring it out from vendor.
