### ISSUE TITLE
Suggest for additional address fields

### ISSUE THREAD

**Issue by humble92** [s-cart/s-cart#57]
Could you add city filed & state field for memeber info?
Currently, `address 2 ` is designed for the rest adress fields, but, most of countries have city name and province(or state) name, so it would be useful for the future. It also helps increase users of this solution over the world.

![image](https://user-images.githubusercontent.com/1191154/107130275-9df34300-6880-11eb-8ffd-5ee7f38a08f1.png)

Thanks for your consideration.

**Comment by lanhktc** [comment]
We will add address 3 column
