### ISSUE TITLE
Wishlist is not working

### ISSUE THREAD

**Issue by humble92** [s-cart/s-cart#58]
**Describe the bug**

Wishlist is not working with message below

**Screenshots**
![image](https://user-images.githubusercontent.com/1191154/107130459-8321ce00-6882-11eb-8e49-ffd8e2207097.png)

**To Reproduce**
1. Go to 'Shop home'
2. Mouse over the product and click heart icon

**Desktop (please complete the following information):**
 - OS: Windows, xampp dev. env.
 - Browser : chrome
 - Version : latest version 88.0.4324.150 (Official Build) (64-bit)

**Additional context**
 - When running a server using 'php artisan', it is working - PHP 7.4.6 (cli) (built: May 12 2020 11:38:54) ( ZTS Visual C++ 2017 x64 )
 - However, when it is running on apache server, above error occurs. - PHP 8.0.0
 - There is no error message in a log file in storage/logs

**Comment by lanhktc** [comment]
Use `php composer.phar update s-cart/core`  or download lasted full source.
