### ISSUE TITLE
View cart is not working

### ISSUE THREAD

**Issue by humble92** [s-cart/s-cart#59]
**Describe the bug**
See capture

**To Reproduce**
1. In main page
2. click cart icon

**Screenshots**

![image](https://user-images.githubusercontent.com/1191154/107130934-35f42b00-6887-11eb-90e5-2df8cf741ada.png)

** possible reason **
New php version seems not allow return bool value

**Desktop (please complete the following information):**
 - OS: Windows, xampp dev. env.
 - Browser : chrome
 - Version : latest version 88.0.4324.150 (Official Build) (64-bit)

**Additional context**
 - When running a server using 'php artisan', it is working - PHP 7.4.6 (cli) (built: May 12 2020 11:38:54) ( ZTS Visual C++ 2017 x64 )
 - However, when it is running on apache server, above error occurs. - PHP 8.0.0

**Comment by humble92** [comment]
If you are pleased, patch the code snippet please:

\vendor\s-cart\core\src\Front\Models\ShopOrderTotal.php: line 80

            return $a['sort'] - $b['sort'];

Thanks for your effort.

**Comment by lanhktc** [comment]
Thanks. We'll fix in next release

**Comment by lanhktc** [comment]
Use `php composer.phar update s-cart/core`  or download lasted full source.
