### ISSUE TITLE
Add to cart is not working

### ISSUE THREAD

**Issue by humble92** [s-cart/s-cart#60]
**Describe the bug**
Add to cart is not working

**To Reproduce**
1. Go to 'Shop home'
2. Mouse over the product and click "ADD TO CART" button

or

Open product page and click "ADD TO CART" button

**Desktop (please complete the following information):**
 - OS: Windows, xampp dev. env.
 - Browser : chrome
 - Version : latest version 88.0.4324.150 (Official Build) (64-bit)

**Additional context**
 - When running a server using 'php artisan', it is working - PHP 7.4.6 (cli) (built: May 12 2020 11:38:54) ( ZTS Visual C++ 2017 x64 )
 - However, when it is running on apache server, above error occurs. - PHP 8.0.0
 - There is no error message in a log file in storage/logs

**Comment by humble92** [comment]
If you are pleased, please use this patch:

- vendor\s-cart\core\src\Library\ShoppingCart\CartItem.php : line 83

public function __construct($id, $name, $price, array $options = [], $tax = 0, $storeId = null)

- vendor\s-cart\core\src\Library\ShoppingCart\CartItem.php : line 242 ~ 246

     * @param int|float  $tax
     * @param int        $storeId
     * @return \SCart\Core\Library\ShoppingCart\CartItem
     */
    public static function fromAttributes($id, $name, $price, array $options = [], $tax = 0, $storeId = null)

**Comment by lanhktc** [comment]
Thanks. We'll fix in next release :)

**Comment by lanhktc** [comment]
Use `php composer.phar update s-cart/core`  or download lasted full source.

**Comment by humble92** [comment]
Thanks for your all recent updates. :)
