### ISSUE TITLE
"Add to Cart button" in wish list page

### ISSUE THREAD

**Issue by humble92** [s-cart/s-cart#63]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Currently, only remove button exists in list. "Add to cart" might be useful because user need not the following procedure: 1) click the each item -> 2) Add to cart -> 3) Return to Wish list

**Describe alternatives you've considered**

Two possible approaches seems to be available here to solve this problem.

1) New button here
No. | SKU | Name | Price | **Action** 

Action column can contain + button and x button: 
  `+ (Copy)` : Copy to Cart, and the item still exists in wishlist
  `+ (Move)` : Move to Cart, and the item is deleted from wishlist
  `x` : Remove button

Customers' favorites shopping item list can be managed with these three buttons because wishlist can be favorites list for now with these three buttons.

2) New button here
No. | SKU | Name | Price | **Add to Card** |  Remove

I think solution 1 is better and flexible for future extendability, but it might retuire a little more work than solution 2.

**Additional context**

![image](https://user-images.githubusercontent.com/1191154/107905769-57e35280-6f04-11eb-8107-3978cad68696.png)

**Comment by lanhktc** [comment]
it appears in premium version :)

**Comment by humble92** [comment]
Oh, I see. Can I ask the other differences of features between 2 versions?

**Comment by lanhktc** [comment]
S-Cart is free with foundation construction and basic functions. Users will customize their own requirements.
The premium version is also built using s-cart/core. However, the template and functions will be better improved.
