### ISSUE TITLE
"DashboardController does not exist" after moving sources from local development env. to hosting server

### ISSUE THREAD

**Issue by humble92** [s-cart/s-cart#72]
Laravel log says as follows:

[previous exception] [object] (ReflectionException(code: -1): Class App\\Admin\\Controllers\\DashboardController does not exist at /var/www/new.vancouverstore.ca/vendor/laravel/framework/src/Illuminate/Container/Container.php:830)

But, actually there is!

$ grep -rH DashboardController *

vendor/composer/autoload_classmap.php:    'SCart\\Core\\Admin\\Controllers\\DashboardController' => $vendorDir . '/s-cart/core/src/Admin/Controllers/DashboardController.php',
vendor/composer/autoload_static.php:        'SCart\\Core\\Admin\\Controllers\\DashboardController' => __DIR__ . '/..' . '/s-cart/core/src/Admin/Controllers/DashboardController.php',
vendor/s-cart/core/src/Admin/Controllers/DashboardController.php:class DashboardController extends RootAdminController
vendor/s-cart/core/src/Admin/routes.php:    Route::get('/', 'DashboardController@index')->name('admin.home');
vendor/s-cart/core/src/Admin/routes.php:    Route::get('deny', 'DashboardController@deny')->name('admin.deny');
vendor/s-cart/core/src/Admin/routes.php:    Route::get('data_not_found', 'DashboardController@dataNotFound')->name('admin.data_not_found');
vendor/s-cart/core/src/Admin/routes.php:    Route::get('deny_single', 'DashboardController@denySingle')->name('admin.deny_single');

How can it be launched? Thanks a lot.

**Comment by lanhktc** [comment]
what's version?

**Comment by humble92** [comment]
The version is 5.0.4, The below could be more helpful:

commit eca4f8ccb3f9d96beec38d3f1b2d81134dac5f26 (HEAD -> master, tag: v5.0.4, origin/master, origin/HEAD)
Merge: f96af5a6 8b6d2b12
Author: Lanh Le <lanhktc@gmail.com>
Date:   Sat Feb 13 21:10:23 2021 +0700

    Merge branch 'dev' into master

**Comment by lanhktc** [comment]
Try download last version

**Comment by humble92** [comment]
Thanks a lot. I will try in a week, and let you know. Thanks again.

**Comment by humble92** [comment]
Yes, it was check and is working good. Thanks a lot. This issue can be closed. Thumbs up!
