### ISSUE TITLE
Không hiển thị menu phần quản trị trong tài khoản khác ngoài tài khoản admin!

### ISSUE THREAD

**Issue by ddai00bit** [s-cart/s-cart#73]
**Describe the bug**
Tôi thử phiên bản s-cart 5.0.6 các hạng mục đều hoạt động ổn với tài khoản quản trị admin!
nhưng khi sử dụng các tài khoản khác đã phân quyền đăng nhập vào thì chỉ có Dashboard , còn lại menu bên trái không xuất hiện như ở tài khoản quản trị menu!

**Comment by lanhktc** [comment]
Bạn thử cập nhật phiên bản mới hơn xem sao
