### ISSUE TITLE
When install s-cart I got this error "Error while create table admin"

### ISSUE THREAD

**Issue by Rominpatel007** [s-cart/s-cart#75]
![image](https://user-images.githubusercontent.com/80568044/112875337-ae39d880-90e1-11eb-8ddb-3f1925ce0ce3.png)

**Comment by lanhktc** [comment]
You try check log error

**Comment by haiproa2** [comment]
i can't find log
![image](https://user-images.githubusercontent.com/13213067/113465617-b4241680-945f-11eb-967d-798b8abdaf60.png)
