### ISSUE TITLE
Base table or view not found

### ISSUE THREAD

**Issue by MarufAhmedRatul** [s-cart/s-cart#76]
I've found an error : 
**SQLSTATE[42S02]: Base table or view not found: 1146 Table 'scart.sc_shop_product_property' doesn't exist (SQL: select `name`, `code` from `sc_shop_product_property`)**

In backend **"Product and Catalog > product manager"** I've found this error. 
![scart-error](https://user-images.githubusercontent.com/13566548/113105279-3c69a800-9223-11eb-8053-5d7113e4cf1c.PNG)

Version : 6.0- beta

**Comment by lanhktc** [comment]
Try download https://s-cart.org/en/download.html
