### ISSUE TITLE
Ckeditor is not shown and javascript error occurs

### ISSUE THREAD

**Issue by humble92** [s-cart/s-cart#77]
**Describe the bug**
Uncaught Syntax javascript error in product edit page.
Ckeditor is not shown and javascript error occurs instead.

**To Reproduce**
1) After updating sql queries for sc_shop_product_description, 
2) go to product edit page

(*) **The same DB & source** was working good with new install following `php artisan sc:recover` in some machine (my local computer), but the same procedure was not working in a server machine. Is this environmental issue? It is still very weird.

**Screenshots**
![image](https://user-images.githubusercontent.com/1191154/114367648-7dba5b80-9b31-11eb-89f6-128883561dcf.png)

(Left: local machine, Right: server machine)

![image](https://user-images.githubusercontent.com/1191154/114367888-bfe39d00-9b31-11eb-82bd-fcdedc20b489.png)

![image](https://user-images.githubusercontent.com/1191154/114367771-a5112880-9b31-11eb-9c3a-fdd8e2c3e902.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser : chrome
 - Version :
commit 087099d9ffb585427b2d9010aab568e9214bf901 (HEAD -> master, tag: v6.0.5, origin/master, origin/HEAD)
Merge: 48d4933c c7dd3fc0
Date:   Fri Apr 9 23:07:49 2021 +0700

Hope this info is helpful.

**Comment by lanhktc** [comment]
It's hard to say exactly what the problem is. Do you check the description content, have escape data, like single quotes ' ?

**Comment by humble92** [comment]
No. It doesn't.

2021년 4월 12일 (월) 오전 5:11, Lanh Le ***@***.***>님이 작성:

**Comment by humble92** [comment]
Correction. I was confused last night. Local is not working as well. 

So, after new installation, CKEdit is working.

The backfile can not be uploaded now because is still broken after bulk update. I am still wondering why it happened.

FYI: This are a few rows of this table:

```
INSERT INTO `sc_shop_product_description` (`product_id`, `lang`, `name`, `keyword`, `description`, `content`) VALUES
(1, 'en', 'AUCHENTOSHAN - AMERICAN OAK', '', '', '<p>Volume: 750 mL</p>'),
(2, 'en', 'ELYSIAN - LOSER PALE ALE', '', '', '<p>Volume: 650 mL</p>'),
(3, 'en', 'Cass', '', '', '<p>Volume: 330 mL<br>Alcohol: 4.5 %</p>'),
(4, 'en', 'VINHO VERDE - VINCENTE FARIA  ANIMUS', '', '', '<p>Volume: 750 mL<br>Alcohol: 10.5 %</p>'),
(5, 'en', 'jagermeister', '', '', '<p>Volume: 1.14 L<br>Alcohol: 35 %</p>'),
(6, 'en', 'jagermeister', '', '', '<p>Volume: 100 mL</p>'),
(7, 'en', 'ORGAIN ORGANIC PROTEIN 12 x330ml', '', '', '<p>Volume: 1 mL</p>'),
(8, 'en', '1707 reserve red - stellenbosch hills stellenbosch 2008', '', '', '<p>Volume: 750 mL</p>'),
(9, 'en', 'BODACIOUS - SMOOTH RED CAN', '', '', '<p>Volume: 250 mL<br>Alcohol: 11 %</p>'),
(10, 'en', 'Absolut', '', '', '<p>Volume: 750 mL<br>Alcohol: 40 %</p>'),
.... etc. ...
```

**Comment by humble92** [comment]
When adding an item, CKEditor is working.

![image](https://user-images.githubusercontent.com/1191154/114487315-3d57ed80-9bc4-11eb-8863-5ccf1eb6a27d.png)

But, after being added, it is not working:

![image](https://user-images.githubusercontent.com/1191154/114487264-25806980-9bc4-11eb-8d8b-616d65f7daa1.png)

![image](https://user-images.githubusercontent.com/1191154/114487437-7001e600-9bc4-11eb-83cd-544a0e00fff3.png)

The source is brand new, so it is very weird. How can the operation depend on DB contents? I am not sure my updating query is actual reason.
