### ISSUE TITLE
Is it possible to rename admin panel?

### ISSUE THREAD

**Issue by emaalouf** [s-cart/s-cart#78]
Dear all,

Is it possible to rename the admin panel from S-Cart Admin to another name for example: Mars Admin?
I tried in the configuration on the left side but it didn't work, I also found that it is seeded into the database but I searched the whole database and couldn't find anything to change.

Best Regards,
Elias,

**Comment by lanhktc** [comment]
This problem wil fix in next update

**Comment by emaalouf** [comment]
Is it fixed in 6.0.6?

**Comment by lanhktc** [comment]
V6.1
