### ISSUE TITLE
Cent value is gone away after saving (at admin order)

### ISSUE THREAD

**Issue by humble92** [s-cart/s-cart#80]
**Describe the bug**
After adding new products in admin order page, cent value is deleted.

**To Reproduce**
/order/detail/
Add product with cent value

**Expected behavior**
Cent value should be kept

**Screenshots**
![image](https://user-images.githubusercontent.com/1191154/115986275-4ea9de00-a564-11eb-96a6-d1f20a447ff4.png)

In the above capture:

1st row: the result after saving
2nd row: the exact price of the above product (before saving)

Total/Subtotal page has the same problem.

![image](https://user-images.githubusercontent.com/1191154/115986486-4605d780-a565-11eb-9611-e42da41b79ce.png)

**Additional context**

commit 087099d9ffb585427b2d9010aab568e9214bf901 (HEAD -> master, tag: v6.0.5, origin/master, origin/HEAD)
Merge: 48d4933c c7dd3fc0

**Comment by humble92** [comment]
I found one of the reasons. DB cannot support USD because of their type. It needs to be corrected. After that it is still needed to accept/handle/present decimal value at UI level.

These queries are what can be fixed in DB schema:


ALTER TABLE `sc_shop_product` CHANGE `price` `price` DECIMAL(7,2) NOT NULL DEFAULT '0', CHANGE `cost` `cost` DECIMAL(7,2) NOT NULL DEFAULT '0';

ALTER TABLE `sc_shop_order_detail` CHANGE `price` `price` DECIMAL(7,2) NOT NULL DEFAULT '0', CHANGE `total_price` `total_price` DECIMAL(7,2) NOT NULL DEFAULT '0';

ALTER TABLE `sc_shop_order` CHANGE `subtotal` `subtotal` DECIMAL(7,2) NULL DEFAULT '0', CHANGE `discount` `discount` DECIMAL(7,2) NULL DEFAULT '0', CHANGE `tax` `tax` DECIMAL(7,2) NULL DEFAULT '0', CHANGE `total` `total` DECIMAL(7,2) NULL DEFAULT '0', CHANGE `received` `received` DECIMAL(7,2) NULL DEFAULT '0', CHANGE `balance` `balance` DECIMAL(7,2) NULL DEFAULT '0';


If you are pleased, could you add them into DB migration?

**Comment by humble92** [comment]
After modifying the fields above, it shows still truncation of cent values for now.

![image](https://user-images.githubusercontent.com/1191154/115998851-20e18b00-a59e-11eb-9c43-341122fbbd1c.png)

**Comment by humble92** [comment]
e.g. sc_tax_price:

This function should be more flexible according to currency setting in admin page. I guess such as  

```
        $price = $price * (100 + $tax) /100;
        $price = number_format((float)$price, THE_GENETATED_VALUE_FROM_CURRENCY_SETTING, '.', '');  // can be 100 or 100.50
```

```
/*
    Return price with tax
*/
if (!function_exists('sc_tax_price')) {
    function sc_tax_price($price, $tax)
    {
        return floor($price * (100 + $tax) /100);
    }
}
```

**Comment by humble92** [comment]
Finally found out sc_currency_format, but not easy to override ShopCurrency::precision, which is hard-coded now.

```
    $price = sc_currency_format($price * (100 + $tax) /100);
    return $price;
```

**Comment by humble92** [comment]
In spite of all work above, the price sum doesn't match and Tax value cannot aceept float type (cent value).

![image](https://user-images.githubusercontent.com/1191154/116002920-b6861600-a5b0-11eb-8b78-a8c7bb0c45ee.png)

I hope it could be patched soon.

**Comment by humble92** [comment]
Another bug:

When tax of 1 is entered, the calculation is broken.

![image](https://user-images.githubusercontent.com/1191154/116003551-44630080-a5b3-11eb-98a6-098095051024.png)

**Comment by lanhktc** [comment]
Currently S-Cart calculations only support integers :)

**Comment by humble92** [comment]
Thanks for the clarification. I hope that to be updated soon.

**Comment by humble92** [comment]
Can I ask one thing to you? To accept float value here, which part should be modified?

![image](https://user-images.githubusercontent.com/1191154/117021445-35173d80-acac-11eb-9bd8-230efca3efcc.png)

It is a little bit difficult for me to find that out. The code snippet below seems not a proper place.

Thanks a lot.

```
    $('.edit-item-detail').editable({
        ajaxOptions: {
        type: 'post',
        dataType: 'json'
        },
        validate: function(value) {
          if (value == '') {
              return '{{  trans('admin.not_empty') }}';
          }
          if (!$.isNumeric(value)) {
              return '{{  trans('admin.only_numeric') }}';
          }
        },
        success: function(response,newValue) {
            if(response.error ==0){
                $('.data-shipping').html(response.detail.shipping);
                $('.data-received').html(response.detail.received);
                $('.data-subtotal').html(response.detail.subtotal);
                $('.data-tax').html(response.detail.tax);
                $('.data-total').html(response.detail.total);
                $('.data-shipping').html(response.detail.shipping);
                $('.data-discount').html(response.detail.discount);
                $('.item_id_'+response.detail.item_id).html(response.detail.item_total_price);
                var objblance = $('.data-balance').eq(0);
                objblance.before(response.detail.balance);
                objblance.remove();
                alertJs('success', response.msg);
            } else {
              alertJs('error', response.msg);
            }
        }

    });
```
