### ISSUE TITLE
data-pk value is different in admin order page

### ISSUE THREAD

**Issue by humble92** [s-cart/s-cart#81]
**Describe the bug**
data-pk value is different in admin order page.
As the caputures shown, data-pk is increasing (3, 4, 6) even though the url address is `admin/order/detail/1`
data-ps should be 1

**To Reproduce**
Try to modify shipping, discount, and received value in admin

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/1191154/117552619-6885ff00-b001-11eb-9725-b760015ff905.png)
![image](https://user-images.githubusercontent.com/1191154/117552682-cb779600-b001-11eb-9169-66997911afdb.png)
![image](https://user-images.githubusercontent.com/1191154/117552705-f1049f80-b001-11eb-9c5c-31a0169f96d9.png)

**Additional context**

**Comment by lanhktc** [comment]
Thanks for report. 
This error fixed. However, it is not relation to pk value. For 6.x, pls hotfix via command line "php composer.phar update s-cart/core".

**Comment by humble92** [comment]
Yeap, found it, too. In spite of my wrong analysis, you did it. Thanks.

`            $orderId = $orderTotalOrigin->order_id;`
