### ISSUE TITLE
Không tìm thấy danh mục sản phẩm khi thêm sản phẩm

### ISSUE THREAD

**Issue by vovantrinh** [s-cart/s-cart#82]
Mình đã tắt ngôn ngữ tiếng Anh và khi thêm 1 một danh mục mới bằng tiếng Việt sau đó qua thêm sản phẩm thì không tìm thấy danh mục đó trong danh sách danh mục.
Hình ảnh danh mục khi ở trang danh mục sản phẩm
![image](https://user-images.githubusercontent.com/30221846/121629995-81714c80-caa6-11eb-8c36-5ca54866be16.png)

Không tìm thấy danh mục khi tạo sản phẩm
![image](https://user-images.githubusercontent.com/30221846/121630070-a9f94680-caa6-11eb-983b-a88558d60c93.png)
 Đồng thời không hiển thị tiếng Việt bên link product

**Comment by lanhktc** [comment]
Cảm ơn bạn. Cập nhật vá lỗi bằng  `php composer.phar update s-cart/core`
