### ISSUE TITLE
`Undefined index:` khi tạo đơn hàng mới

### ISSUE THREAD

**Issue by raymondugv** [s-cart/s-cart#83]
**Describe the bug**
Sau khi nhập thông tin khách hàng ( đối với khách hàng chưa có trong CSDL) sau đó `Gửi` thì xuất hiện lỗi.

**To Reproduce**
1. Vào Quản lý đơn hàng > Đơn hàng
2. Tạo đơn hàng mới
3. Điền thông tin khách hàng
![image](https://user-images.githubusercontent.com/21214764/124650855-68e92c00-dec4-11eb-9809-8500cdc065d3.png)

4. Bấm gửi
5. Thấy lỗi

**Expected behavior**
Sẽ hiện trang để có thể chọn sản phẩm và các bước tiếp theo để thực hiện đơn hàng
![image](https://user-images.githubusercontent.com/21214764/124650953-861dfa80-dec4-11eb-84b0-cfaf6028cbc1.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/21214764/124650744-40f9c880-dec4-11eb-9607-662bdbbb1f4e.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Brave
 - Version [e.g. 22] V1.26.74

**Comment by lanhktc** [comment]
Lỗi này sẽ được được cập nhật trong release core mới nhất: https://github.com/s-cart/core/commit/4afd0e7f5b8d44ace7589b2ea8a1a76cb5fb2759

**Comment by raymondugv** [comment]
> Lỗi này sẽ được được cập nhật trong release core mới nhất: [s-cart/core@4afd0e7](https://github.com/s-cart/core/commit/4afd0e7f5b8d44ace7589b2ea8a1a76cb5fb2759)

Cảm ơn @lanhktc ,

Hông biết giờ mình có thể update phiên bản hiện tại của mình lên để có thể dùng được cái chức năng này như bình thường được chưa nhỉ?.

**Comment by lanhktc** [comment]
Trên S-Cart 6.4, chạy lệnh "php composer.phar update s-cart/core" để vá lỗi

**Comment by raymondugv** [comment]
Xin chào,

Mình có thử chạy lệnh bạn gửi, nhưng vẫn không chạy được, mình vẫn bị lỗi như trên.
![image](https://user-images.githubusercontent.com/21214764/124782228-43186180-df6e-11eb-90a1-f553ccd0d579.png)

**Comment by raymondugv** [comment]
Xin chào,

Mình đã làm theo hướng dẫn và đã thấy lỗi được sửa, nhưng mà còn một số lỗi về dịch thuật vẫn còn hiện ở trên giao diện.
![image](https://user-images.githubusercontent.com/21214764/124784247-f3d33080-df6f-11eb-811a-d9d1c4f8161d.png)

Mình check [s-cart/core@4afd0e7](https://github.com/s-cart/core/commit/4afd0e7f5b8d44ace7589b2ea8a1a76cb5fb2759) thì thấy phần này đã được update rồi, và mình làm sao để có thể nó hiển thị được nhỉ?.
