### ISSUE TITLE
Error while create table shop

### ISSUE THREAD

**Issue by sbiwaichoon** [s-cart/s-cart#84]
**Describe the bug**
I keep getting this error when install s-cart. please assist
![Capture](https://user-images.githubusercontent.com/42166985/124867121-1442cf80-dff0-11eb-9148-daf3d29c1eff.PNG)

**Comment by lanhktc** [comment]
What's version?

Vào Th 5, 8 thg 7, 2021 vào lúc 12:26 sbiwaichoon <
***@***.***> đã viết:
