### ISSUE TITLE
Lỗi kho hàng và số lượng đặt mua

### ISSUE THREAD

**Issue by quangbahoa** [s-cart/s-cart#87]
**Describe the bug**
Khi sản phẩm có số lượng là 1 nhưng vẫn có thể tăng số lượng lên 2 và tiến hành thanh toán bình thường.

**To Reproduce**
1. Đăng một sản phẩm có số lượng là `1`
2. Ra xem sản phẩm đó rồi tăng số lượng lên `2` hoặc bao nhiêu tùy ý, hoặc thêm vào giỏ hàng rồi vào giỏ tăng số lượng lên lớn hơn `1`
3. Tiến hành thanh toán
4. Thanh toán thành công ^^!

**Note:
- Mình nghĩ nên có chế độ nếu kho là `1` thì ẩn `stepper` hoặc có tick bỏ qua hoặc cho phép mua `1` sản phẩm mỗi đơn.

**Comment by lanhktc** [comment]
Chúng ta có các option here
![image](https://user-images.githubusercontent.com/13057715/126019872-12720dc4-1f34-4603-8c23-62158f834555.png)

**Comment by quangbahoa** [comment]
Thanks

**Comment by quangbahoa** [comment]
Sorry mình phải reopen, mình thấy đặt hàng xong mới báo là không đủ, có thể check luôn trong cart hoặc nếu có `1` thì ẩn chọn số lượng không ta?

**Comment by lanhktc** [comment]
Đó là nhu cầu của người dùng thôi. Bạn có thể dùng ajax để kiểm tra stock trước khi add giỏ hàng.
Tuy nhiên nó sẽ xảy ra kịch bản khác, ví dụ khách add vào giỏ hàng khi stock vẫn còn.  Đến khi tiến hành checkout thì hàng đã hết.
