### ISSUE TITLE
Không thể sửa vendor info

### ISSUE THREAD

**Issue by quangbahoa** [s-cart/s-cart#89]
**Describe the bug**
Không sửa, cập nhật được thông tin vendor sau khi đăng ký.

**To Reproduce**
1. Đăng ký vendor tại `https://m-vendor.s-cart.org/vendor_admin/login`
2. Vào đến trang quản trị là dừng ở đó, không thể cập nhật thông tin, click vào upload logo cũng ra bảng cập nhật thông tin hiện tại
3. Ảnh lỗi: https://i.imgur.com/PeORDsb.png

**Comment by lanhktc** [comment]
1. Vendor bắt buộc phải tạo cửa hàng trước khi có thể có các thao tác khác
2. Lỗi tạo cửa hàng của vendor đã được sửa xong
