### ISSUE TITLE
Nhóm thuộc tính không hiện nếu Đặc tính tắt

### ISSUE THREAD

**Issue by quangbahoa** [s-cart/s-cart#90]
**Describe the bug**
Nhóm thuộc tính `color` - `size` hay `custom` không hiện nếu mục `Sử dụng PHÂN LOẠI ĐẶC TÍNH: download, vật lý, dịch vụ,..` tắt.

To Reproduce**
1. Xóa thuộc tính mặc định -> tạo các thuộc tính mới tại `/attribute_group`
2. Vào Cấu hình cửa hàng `/store_config` -> sản phẩm -> uncheck `Sử dụng PHÂN LOẠI ĐẶC TÍNH: download, vật lý, dịch vụ,..`
3. Tạo hoặc sửa sản phẩm, thêm thuộc tính và giá tiền cộng thêm
4. Ngoài frontend không hiển thị gì thêm.

**Comment by meesudzu** [comment]
Lỗi ở đoạn này nè.
resources/views/templates/s-cart-light/screen/shop_product_detail.blade.php:97
`@if (sc_config('product_property'))`
sửa thành
`@if (sc_config('product_attribute'))`
