### ISSUE TITLE
Giá bị sai, bị cộng mỗi khi sửa giá

### ISSUE THREAD

**Issue by quangbahoa** [s-cart/s-cart#91]
**Describe the bug**
Giá hiển thị ngoài frontend cho sản phẩm và cả thuộc tính đều sai.

**To Reproduce**
1. Cấu hình sản phẩm https://i.imgur.com/f9V5UOA.png
2. Tạo sản phẩm, đặt giá https://i.imgur.com/hayt1rt.png
3. Thêm thuộc tính và giá cộng thêm https://i.imgur.com/kaZVBwM.png
4. Sửa giá sản phẩm thành bất kỳ
5. Kết quả https://i.imgur.com/jus1CAS.png

**Comment by lanhktc** [comment]
Tất cả đơn vị giá của sản phẩm, thuộc tính trong admin đều tính đơn vi là Bit, nghĩa là chưa quy đổi theo tiền tệ

**Comment by meesudzu** [comment]
mẹo cho bạn muốn dùng giá VNĐ làm giá chính nè.
vào phần quản lý tiền tệ. đặt tỉ giá là 1, đô nếu không dùng có thể tắt đi hoặc để tỉ giá 0.001.
xong từ giờ nhập giá mặc định sẽ tính theo VNĐ

**Comment by quangbahoa** [comment]
> mẹo cho bạn muốn dùng giá VNĐ làm giá chính nè.
> vào phần quản lý tiền tệ. đặt tỉ giá VNĐ là 1, đô nếu không dùng có thể tắt đi.
> xong từ giờ nhập giá mặc định sẽ tính theo VNĐ

Thanks cậu
