### ISSUE TITLE
Lỗi khi tính giá trong đơn hàng

### ISSUE THREAD

**Issue by meesudzu** [s-cart/s-cart#94]
**Describe the bug**
1. Các mục giảm giá, đã nhận đều bị tính (+) trong khi đó ngược phải là tính trừ (-)
Ps: chỗ này mình thấy nếu nhập giá có dấu '-' thì sẽ đúng, có thể là tác giả muốn để như vậy.
AdminOrder@updateRowOrderTotal
![image](https://user-images.githubusercontent.com/17334624/127837461-c049db94-204b-499d-bc51-4c6a8174aac9.png)
2. Tính giá  của từng sản phẩm trong đơn hàng đang bị sai khi có thuế do chưa bắt field 'tax', chỉ bắt field 'qty'
AdminOrderController@postEditItem
![image](https://user-images.githubusercontent.com/17334624/127837517-35472413-1be1-46f5-be1a-123ac4570962.png)

**Comment by lanhktc** [comment]
Thanks
1. Discount sử dụng giá trị âm (-)
2. Lỗi khi update tax trong admin đã được sửa lại https://github.com/s-cart/core/commit/f1e571fe2480c1a7268666b9547d9c8e9b4972ae
