### ISSUE TITLE
Server Error 500 on User Permissions Page

### ISSUE THREAD

**Issue by asfarul** [s-cart/s-cart#96]
Hello, i got a 500 server error page when i open the Permission menu in Admin Panel (User Permission > Permission). It happened when i firstly installed s-cart version 6.5.0.

1. Go to Admin Panel
2. Click on User Permission > Permission
4. See error 500

**S-Cart Core Verson is 6.5.0**

I have tried to tracking the error, it's caused the routes data failed to get in PermissionController.php
at $routes = app()->routes()->getRoutes();

    public function __construct()
    {
        parent::__construct();
        $routes = app()->routes->getRoutes(); //the problem is here
        // dd($routes);
        foreach ($routes as $route) {
            if (Str::startsWith($route->uri(), SC_ADMIN_PREFIX)) {
                $prefix = SC_ADMIN_PREFIX?$route->getPrefix():ltrim($route->getPrefix(),'/');
                $routeAdmin[$prefix] = [
                    'uri'    => 'ANY::' . $prefix . '/*',
                    'name'   => $prefix . '/*',
                    'method' => 'ANY',
                ];`

and this is the Error log:

<pre>
[2021-09-14 10:09:18] local.ERROR: 2021-09-14 10:09:18:
```Target class [routes] does not exist.```
*File* `G:\WebDev\scart-web\vendor\laravel\framework\src\Illuminate\Container\Container.php`, *Line:* 875, *Code:* 0
URL= http://127.0.0.1:8000/admin_panel/permission
  
[2021-09-14 10:09:18] local.ERROR: Target class [routes] does not exist. {"exception":"[object] (Illuminate\\Contracts\\Container\\BindingResolutionException(code: 0): Target class [routes] does not exist. at G:\\WebDev\\scart-web\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php:875)
[stacktrace]
#0 G:\\WebDev\\scart-web\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(754): Illuminate\\Container\\Container->build('routes')
#1 G:\\WebDev\\scart-web\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(841): Illuminate\\Container\\Container->resolve('routes', Array, true)
#2 G:\\WebDev\\scart-web\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(692): Illuminate\\Foundation\\Application->resolve('routes', Array)
#3 G:\\WebDev\\scart-web\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(826): Illuminate\\Container\\Container->make('routes', Array)
#4 G:\\WebDev\\scart-web\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(1420): Illuminate\\Foundation\\Application->make('routes')
#5 G:\\WebDev\\scart-web\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(1458): Illuminate\\Container\\Container->offsetGet('routes')
#6 G:\\WebDev\\scart-web\\vendor\\s-cart\\core\\src\\Admin\\Controllers\\Auth\\PermissionController.php(19): Illuminate\\Container\\Container->__get('routes')
#7 G:\\WebDev\\scart-web\\app\\Admin\\Controllers\\Auth\\PermissionController.php(8): SCart\\Core\\Admin\\Controllers\\Auth\\PermissionController->__construct()
#8 [internal function]: App\\Admin\\Controllers\\Auth\\PermissionController->__construct()
#9 G:\\WebDev\\scart-web\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(917): ReflectionClass->newInstanceArgs(Array)
#10 G:\\WebDev\\scart-web\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(754): Illuminate\\Container\\Container->build('App\\\\Admin\\\\Contr...')
#11 G:\\WebDev\\scart-web\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(841): Illuminate\\Container\\Container->resolve('App\\\\Admin\\\\Contr...', Array, true)
#12 G:\\WebDev\\scart-web\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(692): Illuminate\\Foundation\\Application->resolve('App\\\\Admin\\\\Contr...', Array)
#13 G:\\WebDev\\scart-web\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(826): Illuminate\\Container\\Container->make('App\\\\Admin\\\\Contr...', Array)
#14 G:\\WebDev\\scart-web\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(275): Illuminate\\Foundation\\Application->make('App\\\\Admin\\\\Contr...')
#15 G:\\WebDev\\scart-web\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(1049): Illuminate\\Routing\\Route->getController()
#16 G:\\WebDev\\scart-web\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(1010): Illuminate\\Routing\\Route->controllerMiddleware()
#17 G:\\WebDev\\scart-web\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(708): Illuminate\\Routing\\Route->gatherMiddleware()
#18 G:\\WebDev\\scart-web\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(688): Illuminate\\Routing\\Router->gatherRouteMiddleware(Object(Illuminate\\Routing\\Route))
#19 G:\\WebDev\\scart-web\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#20 G:\\WebDev\\scart-web\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(636): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#21 G:\\WebDev\\scart-web\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#22 G:\\WebDev\\scart-web\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(166): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#23 G:\\WebDev\\scart-web\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#24 G:\\WebDev\\scart-web\\vendor\\barryvdh\\laravel-debugbar\\src\\Middleware\\InjectDebugbar.php(60): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 G:\\WebDev\\scart-web\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 G:\\WebDev\\scart-web\\vendor\\spatie\\laravel-pjax\\src\\Middleware\\FilterIfPjax.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 G:\\WebDev\\scart-web\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Spatie\\Pjax\\Middleware\\FilterIfPjax->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 G:\\WebDev\\scart-web\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 G:\\WebDev\\scart-web\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 G:\\WebDev\\scart-web\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 G:\\WebDev\\scart-web\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 G:\\WebDev\\scart-web\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 G:\\WebDev\\scart-web\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 G:\\WebDev\\scart-web\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 G:\\WebDev\\scart-web\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 G:\\WebDev\\scart-web\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 G:\\WebDev\\scart-web\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 G:\\WebDev\\scart-web\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\Middleware\\TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 G:\\WebDev\\scart-web\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 G:\\WebDev\\scart-web\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 G:\\WebDev\\scart-web\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#42 G:\\WebDev\\scart-web\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#43 G:\\WebDev\\scart-web\\public\\index.php(82): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#44 G:\\WebDev\\scart-web\\server.php(21): require_once('G:\\\\WebDev\\\\scart-w...')
#45 {main}
</pre>

**Expected behavior**
it would be show the permission list (permission page like the other page menu)

**Screenshots**
![image](https://user-images.githubusercontent.com/13598088/133181229-04cb193f-c1bf-4705-89c4-1cb5b176a377.png)

**Desktop:**
 - OS: Windows 10
 - Browser Chrome
 - Version 93

Thanks before,

**Comment by lanhktc** [comment]
@asfarul  Try uncomment https://github.com/s-cart/s-cart/blob/master/app/Providers/RouteServiceProvider.php#L29

**Comment by asfarul** [comment]
now it's working. thank you so much :)
