### ISSUE TITLE
Không ẩn được menu của admin user

### ISSUE THREAD

**Issue by ThanhNguyenDo** [s-cart/s-cart#97]
**Describe the bug**

**To Reproduce**
1. Go to 'admin_menu' và chuyển hiden về 1
2. Quay lại menu admin
3. Menu vẫn hiển thị

**Expected behavior**
Khi chỉnh hidden về 1 cho menu_admin, menu nên ẩn đi

**Screenshots**
Nguyên nhân: self::$getList dùng chung với hiển thị tất cả và hidden nên khi chỉnh không có tác dụng

public static function getListAllDisplay()
    {
        if (self::$getList == null) {
            self::$getList = self::orderBy('sort', 'asc')
            ->where('hidden', 0)
            ->get();
        }
        return self::$getList;
    }

cách sửa:
thêm 
private static $getListDisplay = null;

và sửa thành:
 public static function getListAllDisplay()
    {
        if (self::$getListDisplay == null) {
            self::$getListDisplay = self::orderBy('sort', 'asc')
            ->where('hidden', 0)
            ->get();
        }
        return self::$getListDisplay;
    }

**Comment by lanhktc** [comment]
Fixed https://github.com/s-cart/core/commit/27200a0072a53612ca4c85c347f82055f4ac6a4a
