### ISSUE TITLE
Không xóa được sub ảnh trong product/ sản phẩm

### ISSUE THREAD

**Issue by ThanhNguyenDo** [s-cart/s-cart#98]
**Describe the bug**

**To Reproduce**
1. Go to 'Admin\Sản phẩm'
2. Vào edit 1 sản phẩm để xoá hết ảnh phụ
3. Submit
4. Nếu xoá hết sub ảnh sẽ k update được, luôn phải để lại 2 ảnh, 1 ảnh chính và 1 ảnh phụ

**Expected behavior**
Cho phép xoá hết ảnh phụ

**Root cause analysis**

//Update sub mages
AdminProductController
        if ($subImages && in_array($product['kind'], [SC_PRODUCT_SINGLE, SC_PRODUCT_BUILD])) {
            $product->images()->delete();
            $arrSubImages = [];
            foreach ($subImages as $key => $image) {
                if ($image) {
                    $arrSubImages[] = new ShopProductImage(['image' => $image]);
                }
            }
            $product->images()->saveMany($arrSubImages);
        }

Khi $subImages length = 0 thì sẽ không vào được block if này

**Comment by lanhktc** [comment]
@ThanhNguyenDo 
Fixed https://github.com/s-cart/core/commit/c45187035a6d6038205b0ea8f6208fc0b7a641be
Pls run `php composer.phar update s-cart/core`
Thanks.
